import Util from "../../helpers/Util";

const PluginEvents = {
  "STARTUP_COMPLETE": "STARTUP_COMPLETE",
  "INJECT_COMPONENT": "INJECT_COMPONENT",
  "APPS_STORE_CHANGE": "APPS_STORE_CHANGE",
  "APP_FORM_STORE_INSERT": "APP_FORM_STORE_INSERT",
  "APP_FORM_STORE_UPDATE": "APP_FORM_STORE_UPDATE",
  "APP_FORM_STORE_DELETE": "APP_FORM_STORE_DELETE",
  "APP_FORM_STORE_CHANGE": "APP_FORM_STORE_CHANGE"
};

export default Util.fixObject(PluginEvents, "PLUGIN_EVENTS_");
