var DeploymentEvents = {
  CHANGE: "DEPLOYMENT_EVENTS_CHANGE",
  REQUEST: "DEPLOYMENT_EVENTS_REQUEST",
  REQUEST_ERROR: "DEPLOYMENT_EVENTS_REQUEST_ERROR",
  REVERT: "DEPLOYMENT_EVENTS_REVERT",
  REVERT_ERROR: "DEPLOYMENT_EVENTS_REVERT_ERROR"
};

module.exports = DeploymentEvents;
