var AppsEvents = {
  CHANGE: "APPS_EVENTS_CHANGE",
  REQUEST_APPS: "APPS_EVENTS_REQUEST_APPS",
  REQUEST_APPS_ERROR: "APPS_EVENTS_REQUEST_APPS_ERROR",
  REQUEST_APP: "APPS_EVENTS_REQUEST_APP",
  REQUEST_APP_ERROR: "APPS_EVENTS_REQUEST_APP_ERROR",
  DELETE_APP: "APPS_EVENTS_REQUEST_APP",
  DELETE_APP_ERROR: "APPS_EVENTS_REQUEST_APP_ERROR"
};

module.exports = AppsEvents;
