var AppVersionsEvents = {
  CHANGE: "APP_VERSIONS_EVENTS_CHANGE",
  REQUEST_APP_VERSIONS: "APP_VERSIONS_EVENTS_REQUEST_APP_VERSIONS",
  REQUEST_APP_VERSIONS_ERROR: "APP_VERSIONS_EVENTS_REQUEST_APP_VERSIONS_ERROR",
  REQUEST_APP_VERSION: "APP_VERSIONS_EVENTS_REQUEST_APP_VERSION",
  REQUEST_APP_VERSION_ERROR: "APP_VERSIONS_EVENTS_REQUEST_APP_VERSION_ERROR"
};

module.exports = AppVersionsEvents;
