var AppVersionsEvents = {
  CHANGE: "APP_VERSIONS_EVENTS_CHANGE",
  REQUEST_VERSION_TIMESTAMPS: "APP_VERSIONS_EVENTS_VERSION_TIMESTAMPS",
  REQUEST_VERSION_TIMESTAMPS_ERROR: "APP_VERSIONS_EVENTS_VERSION_TIMESTAMPS_ERROR",
  REQUEST_ONE: "APP_VERSIONS_EVENTS_REQUEST_ONE",
  REQUEST_ONE_ERROR: "APP_VERSIONS_EVENTS_REQUEST_ONE_ERROR"
};

module.exports = AppVersionsEvents;
