const DCOSEvents = Object.freeze({
  REQUEST_BUILD_INFORMATION_COMPLETE:
    "DCOS_EVENTS_REQUEST_BUILD_INFORMATION_COMPLETE",
  REQUEST_BUILD_INFORMATION_ERROR: "DCOS_EVENTS_REQUEST_BUILD_INFORMATION_ERROR"
});

module.exports = DCOSEvents;
