const DeploymentEvents = {
  CHANGE: "DEPLOYMENT_EVENTS_CHANGE",
  REQUEST: "DEPLOYMENT_EVENTS_REQUEST",
  REQUEST_ERROR: "DEPLOYMENT_EVENTS_REQUEST_ERROR",
  REVERT: "DEPLOYMENT_EVENTS_REVERT",
  REVERT_ERROR: "DEPLOYMENT_EVENTS_REVERT_ERROR",
  STOP: "DEPLOYMENT_EVENTS_STOP",
  STOP_ERROR: "DEPLOYMENT_EVENTS_STOP_ERROR"
};

module.exports = Object.freeze(DeploymentEvents);
