const DeploymentEvents = {
  CHANGE: "DEPLOYMENT_EVENTS_CHANGE",
  REQUEST: "DEPLOYMENT_EVENTS_REQUEST",
  REQUEST_ERROR: "DEPLOYMENT_EVENTS_REQUEST_ERROR",
  REVERT: "DEPLOYMENT_EVENTS_REVERT",
  REVERT_ERROR: "DEPLOYMENT_EVENTS_REVERT_ERROR",
  CONTINUE_MIGRATION_SUCCESS: "DEPLOYMENT_EVENTS_CONTINUE_MIGRATION_SUCCESS",
  CONTINUE_MIGRATION_ERROR: "DEPLOYMENT_EVENTS_CONTINUE_MIGRATION_ERROR"
};

export default Object.freeze(DeploymentEvents);
