const DialogEvents = {
  ALERT_SHOW: "DIALOG_EVENTS_ALERT_SHOW",
  ALERT_CLOSE: "DIALOG_EVENTS_ALERT_CLOSE",
  CONFIRM_SHOW: "DIALOG_EVENTS_CONFIRM_SHOW",
  CONFIRM_CLOSE: "DIALOG_EVENTS_CONFIRM_CLOSE",
  CONFIRM_ACCEPT: "DIALOG_EVENTS_CONFIRM_ACCEPT",
  PROMPT_SHOW: "DIALOG_EVENTS_PROMPT_SHOW",
  PROMPT_CLOSE: "DIALOG_EVENTS_PROMPT_CLOSE",
  PROMPT_ACCEPT: "DIALOG_EVENTS_PROMPT_ACCEPT"
};

module.exports = Object.freeze(DialogEvents);
