const DialogEvents = {
  ALERT: "DIALOG_EVENTS_ALERT",
  ALERT_CLOSE: "DIALOG_EVENTS_ALERT_CLOSE",
  CONFIRM: "DIALOG_EVENTS_CONFIRM",
  CONFIRM_CLOSE: "DIALOG_EVENTS_CONFIRM_CLOSE",
  CONFIRM_ACCEPT: "DIALOG_EVENTS_CONFIRM_ACCEPT",
  PROMPT: "DIALOG_EVENTS_PROMPT",
  PROMPT_CLOSE: "DIALOG_EVENTS_PROMPT_CLOSE",
  PROMPT_ACCEPT: "DIALOG_EVENTS_PROMPT_ACCEPT"
};

module.exports = Object.freeze(DialogEvents);
