const DialogEvents = {
  ALERT_SHOW: "DIALOG_EVENTS_ALERT_SHOW",
  ALERT_DISMISS: "DIALOG_EVENTS_ALERT_DISMISS",
  CONFIRM_SHOW: "DIALOG_EVENTS_CONFIRM_SHOW",
  CONFIRM_DISMISS: "DIALOG_EVENTS_CONFIRM_DISMISS",
  CONFIRM_ACCEPT: "DIALOG_EVENTS_CONFIRM_ACCEPT",
  PROMPT_SHOW: "DIALOG_EVENTS_PROMPT_SHOW",
  PROMPT_DISMISS: "DIALOG_EVENTS_PROMPT_DISMISS",
  PROMPT_ACCEPT: "DIALOG_EVENTS_PROMPT_ACCEPT",
  DISMISS_LATEST: "DIALOG_EVENTS_DISMISS_LATEST"
};

module.exports = Object.freeze(DialogEvents);
