const FormEvents = {
  CHANGE: "FORM_EVENTS_CHANGED",
  DELETE: "FORM_EVENTS_DELETE",
  FIELD_VALIDATION_ERROR: "FORM_EVENTS_FIELD_VALIDATION_ERROR",
  INSERT: "FORM_EVENTS_INSERT",
  UPDATE: "FORM_EVENTS_UPDATE"
};

module.exports = Object.freeze(FormEvents);
