const GroupsEvents = {
  CREATE_GROUP: "GROUPS_EVENTS_CREATE_GROUP",
  CREATE_GROUP_ERROR: "GROUPS_EVENTS_CREATE_GROUP_ERROR",
  SCALE_SUCCESS: "GROUPS_EVENTS_SCALE_SUCCESS",
  SCALE_ERROR: "GROUPS_EVENTS_SCALE_ERROR",
  DELETE_SUCCESS: "GROUPS_EVENTS_DELETE_SUCCESS",
  DELETE_ERROR: "GROUPS_EVENTS_DELETE_ERROR"
};

export default Object.freeze(GroupsEvents);
