const GroupsEvents = {
  SCALE_SUCCESS: "GROUPS_EVENTS_SCALE_SUCCESS",
  SCALE_ERROR: "GROUPS_EVENTS_SCALE_ERROR",
  DELETE_SUCCESS: "GROUPS_EVENTS_DELETE_SUCCESS",
  DELETE_ERROR: "GROUPS_EVENTS_DELETE_ERROR"
};

export default Object.freeze(GroupsEvents);
