const MesosEvents = Object.freeze({
  CHANGE: "MESOS_EVENTS_CHANGE",
  STATE_CHANGE: "MESOS_EVENTS_STATE_CHANGE",
  TASK_FILE_CHANGE: "MESOS_EVENTS_TASK_FILE_CHANGE",
  REQUEST_VERSION_INFORMATION_COMPLETE:
    "MESOS_EVENTS_REQUEST_VERSION_INFORMATION_COMPLETE",
  REQUEST_VERSION_INFORMATION_ERROR:
    "MESOS_EVENTS_REQUEST_VERSION_INFORMATION_ERROR",
  REQUEST_STATE_COMPLETE: "MESOS_EVENTS_REQUEST_STATE_COMPLETE",
  REQUEST_STATE_ERROR: "MESOS_EVENTS_REQUEST_STATE_ERROR",
  REQUEST_TASK_FILES: "MESOS_EVENTS_REQUEST_TASK_FILES",
  REQUEST_FILES_COMPLETE: "MESOS_EVENTS_REQUEST_FILES_COMPLETE",
  REQUEST_FILES_ERROR: "MESOS_EVENTS_REQUEST_FILES_ERROR"
});

module.exports = MesosEvents;
