const MesosEvents = Object.freeze({
  CHANGE: "MESOS_EVENTS_CHANGE",
  REQUEST_STATE: "MESOS_EVENTS_REQUEST_STATE",
  REQUEST_STATE_ERROR: "MESOS_EVENTS_REQUEST_STATE_ERROR",
  REQUEST_FILES: "MESOS_EVENTS_REQUEST_FILES",
  REQUEST_FILES_ERROR: "MESOS_EVENTS_REQUEST_FILES_ERROR"
});

export default MesosEvents;
