const PluginEvents = {
  CHANGE: "PLUGIN_EVENTS_CHANGE",
  LOAD_PLUGIN_SUCCESS: "PLUGIN_EVENTS_LOAD_PLUGIN_SUCCESS",
  LOAD_PLUGIN_ERROR: "PLUGIN_EVENTS_LOAD_PLUGIN_ERROR",
  REQUEST_PLUGINS_SUCCESS: "PLUGIN_EVENTS_REQUEST_PLUGINS_SUCCESS",
  REQUEST_PLUGINS_ERROR: "PLUGIN_EVENTS_REQUEST_PLUGINS_ERROR",
  OPTIONAL_PORTS_AND_SERVICE_DISCOVERY: "OPTIONAL_PORTS_AND_SERVICE_DISCOVERY"
};

export default Object.freeze(PluginEvents);
