const PluginEvents = {
  META_INFO_SUCCESS: "PLUGIN_EVENTS_META_INFO_SUCCESS",
  META_INFO_ERROR: "PLUGIN_EVENTS_META_INFO_ERROR",
  REQUEST_SUCCESS: "PLUGIN_EVENTS_REQUEST_SUCCESS",
  REQUEST_ERROR: "PLUGIN_EVENTS_REQUEST_ERROR",
  BOOTSTRAP_COMPLETE: "PLUGIN_EVENTS_BOOTSTRAP_COMPLETE"
};

export default Object.freeze(PluginEvents);
