const QueueEvents = {
  CHANGE: "QUEUE_EVENTS_CHANGE",
  REQUEST: "QUEUE_EVENTS_REQUEST",
  REQUEST_ERROR: "QUEUE_EVENTS_REQUEST_ERROR",
  RESET_DELAY: "QUEUE_EVENTS_RESET_DELAY",
  RESET_DELAY_ERROR: "QUEUE_EVENTS_RESET_DELAY_ERROR"
};

module.exports = Object.freeze(QueueEvents);
